name: CI Testing
on: [push, pull_request]
jobs:
  test7:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-build') }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update

      - name: Prepare container
        run: |
          docker pull ghcr.io/netivism/docker-neticrm-ci:drone-php7
          docker run -d --name neticrm-ci -p 8080:8080 -v $GITHUB_WORKSPACE:/mnt/neticrm-7/civicrm -e "DRUPAL=7" -e "TZ=Asia/Taipei" -e "RUNPORT=8080" -e "DRUPAL_ROOT=/var/www/html" -e "CIVICRM_TEST_DSN=mysql://root@localhost/neticrmci" ghcr.io/netivism/docker-neticrm-ci:drone-php7

      - name: Install netiCRM
        run: |
          docker exec neticrm-ci /init.sh
          docker exec neticrm-ci bash -c "cd /var/www/html && drush status | grep version"
          docker exec neticrm-ci bash -c "php -v"
      - name: Frontend - Contribution Editing - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/new_contribution.spec.js"
      - name: Collect error logs on failure
        if: failure()
        run: |
          echo "=== Docker container logs ==="
          docker logs neticrm-ci
          echo "=== PHP error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/php_errors.log ]; then tail -100 /var/www/html/log/php_errors.log; fi"
          echo "=== Drupal error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/drupal.log ]; then tail -100 /var/www/html/log/drupal.log; fi"
          echo "=== Apache error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/apache2/error.log ]; then tail -100 /var/www/html/log/apache2/error.log; fi"
          echo "=== Drupal watchdog logs ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush watchdog:show --count=50 --severity=Error,Critical,Alert,Emergency"
          echo "=== Drupal status ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush status"
      - name: Frontend - Advanced Search - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/advanced_search.spec.js"
      - name: Frontend - Group Editing - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/add_group.spec.js"
      - name: Frontend - Check Membership Type - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/check_membership.spec.js"
      - name: Frontend - Import Records - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/import.spec.js"
      - name: Frontend - Event Normal Registration - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_normal_register.spec.js"
      - name: Frontend - Event Registration for limited participants without waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_nowait_register.spec.js"
      - name: Frontend - Event Registration for limited participants with waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_wait_register.spec.js"
      - name: Frontend - Event Registration for limited participants required approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_approval_register.spec.js"
      - name: Frontend - Event Registration for unlimited participants require approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_unlimit_approval_register.spec.js"
      - name: Frontend - Participant Editing - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_participant.spec.js"
      - name: Frontend - Mailing Editing - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/edit_mailing.spec.js"
      - name: Frontend - Contribution Booster - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/contribution_booster.spec.js"
      - name: Frontend - Report Page Checking - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/report_check.spec.js"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-test7
          path: tests/playwright/playwright-report
          retention-days: 30

  test8:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-build') }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update

      - name: Prepare container
        run: |
          docker pull ghcr.io/netivism/docker-neticrm-ci:drone-php8
          docker run -d --name neticrm-ci -p 8080:8080 -v $GITHUB_WORKSPACE:/mnt/neticrm-7/civicrm -e "DRUPAL=7" -e "TZ=Asia/Taipei" -e "RUNPORT=8080" -e "DRUPAL_ROOT=/var/www/html" -e "CIVICRM_TEST_DSN=mysql://root@localhost/neticrmci" ghcr.io/netivism/docker-neticrm-ci:drone-php8

      - name: Install netiCRM
        run: |
          docker exec neticrm-ci /init.sh
          docker exec neticrm-ci bash -c "cd /var/www/html && drush status | grep version"
          docker exec neticrm-ci bash -c "php -v"
      - name: Frontend - Contribution Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/new_contribution.spec.js"
      - name: Collect error logs on failure
        if: failure()
        run: |
          echo "=== Docker container logs ==="
          docker logs neticrm-ci
          echo "=== PHP error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/php_errors.log ]; then tail -100 /var/www/html/log/php_errors.log; fi"
          echo "=== Drupal error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/drupal.log ]; then tail -100 /var/www/html/log/drupal.log; fi"
          echo "=== Drupal watchdog logs ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush watchdog:show --count=50 --severity=Error,Critical,Alert,Emergency"
          echo "=== Drupal status ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush status"
      - name: Frontend - Advanced Search - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/advanced_search.spec.js"
      - name: Frontend - Group Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/add_group.spec.js"
      - name: Frontend - Check Membership - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/check_membership.spec.js"
      - name: Frontend - Import Records - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/import.spec.js"
      - name: Frontend - Event Normal Registration - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_normal_register.spec.js"
      - name: Frontend - Event Registration for limited participants without waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_nowait_register.spec.js"
      - name: Frontend - Event Registration for limited participants with waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_wait_register.spec.js"
      - name: Frontend - Event Registration for limited participants required approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_approval_register.spec.js"
      - name: Frontend - Event Registration for unlimited participants require approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_unlimit_approval_register.spec.js"
      - name: Frontend - Participant Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/event_participant.spec.js"
      - name: Frontend - Mailing Editing - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/edit_mailing.spec.js"
      - name: Frontend - Contribution Booster - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/contribution_booster.spec.js"
      - name: Frontend - Report Page Checking - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/playwright/ && npx playwright test tests/report_check.spec.js"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-test8
          path: tests/playwright/playwright-report
          retention-days: 30

  test8-d10:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-build') }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update
          cd $GITHUB_WORKSPACE/drupal && git checkout 9.x-develop && git pull
          cd $GITHUB_WORKSPACE/neticrm && git checkout 9.x-develop && git pull

      - name: Prepare container
        run: |
          docker pull ghcr.io/netivism/docker-neticrm-ci:drone-php83-d10
          docker run -d --name neticrm-ci -p 8080:8080 -v $GITHUB_WORKSPACE:/mnt/neticrm-10/civicrm -e "DRUPAL=10" -e "TZ=Asia/Taipei" -e "RUNPORT=8080" -e "DRUPAL_ROOT=/var/www/html" -e "CIVICRM_TEST_DSN=mysql://root@localhost/neticrmci" ghcr.io/netivism/docker-neticrm-ci:drone-php83-d10

      - name: Install netiCRM
        run: |
          docker exec neticrm-ci /init.sh
          docker exec neticrm-ci bash -c "cd /var/www/html && drush status | grep version"
          docker exec neticrm-ci bash -c "php -v"
      - name: Frontend - Contribution Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/new_contribution.spec.js"
      - name: Collect error logs on failure
        if: failure()
        run: |
          echo "=== Docker container logs ==="
          docker logs neticrm-ci
          echo "=== PHP error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/php_errors.log ]; then tail -100 /var/www/html/log/php_errors.log; fi"
          echo "=== Drupal error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/drupal.log ]; then tail -100 /var/www/html/log/drupal.log; fi"
          echo "=== Apache error logs ==="
          docker exec neticrm-ci bash -c "if [ -f /var/www/html/log/apache2/error.log ]; then tail -100 /var/www/html/log/apache2/error.log; fi"
          echo "=== Drupal watchdog logs ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush watchdog:show --count=50 --severity=Error,Critical,Alert,Emergency"
          echo "=== Drupal status ==="
          docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT && drush status"
      - name: Frontend - Advanced Search - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/advanced_search.spec.js"
      - name: Frontend - Group Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/add_group.spec.js"
      - name: Frontend - Check Membership - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/check_membership.spec.js"
      - name: Frontend - Import Records - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/import.spec.js"
      - name: Frontend - Event Normal Registration - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_normal_register.spec.js"
      - name: Frontend - Event Registration for limited participants without waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_nowait_register.spec.js"
      - name: Frontend - Event Registration for limited participants with waitlist - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_wait_register.spec.js"
      - name: Frontend - Event Registration for limited participants required approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_limit_approval_register.spec.js"
      - name: Frontend - Event Registration for unlimited participants require approval - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_unlimit_approval_register.spec.js"
      - name: Frontend - Participant Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/event_participant.spec.js"
      - name: Frontend - Mailing Editing - Playwright
        run: docker exec neticrm-ci  bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/edit_mailing.spec.js"
      - name: Frontend - Contribution Booster - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/contribution_booster.spec.js"
      - name: Frontend - Report Page Checking - Playwright
        run: docker exec neticrm-ci bash -c "cd \$DRUPAL_ROOT/modules/civicrm/tests/playwright/ && npx playwright test tests/report_check.spec.js"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-test8-d10
          path: tests/playwright/playwright-report
          retention-days: 30

  notification:
    if: ${{ failure() }}
    needs: [test7, test8, test8-d10]
    runs-on: ubuntu-latest
    steps:
      - name: Shorten sha
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.NETIVISM_EMAIL_HOST}}
          server_port: ${{secrets.NETIVISM_EMAIL_PORT}}
          username: ${{secrets.NETIVISM_EMAIL_LOGIN}}
          password: ${{secrets.NETIVISM_EMAIL_PASSWD}}
          to: ${{secrets.NETIVISM_NOTIFICATION_TARGET}}
          from: Github Workflow
          secure: false
          ignore_cert: true
          convert_markdown: true
          subject: '[${{github.repository}}] Run failed: ${{github.workflow}} - ${{github.ref_name}} (${{steps.vars.outputs.sha_short}})'
          body: |
            Executed by: ${{github.actor}}
            Job name: ${{github.job}}
            Repository: ${{github.repository}}
            Status: ${{job.status}}
            SHA: ${{github.sha}}
            Message: ${{ github.event.head_commit.message }}
            Link: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
